name: medsuraksha
description: AI Powered Medicine Verification App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  lottie: ^3.5.1
  glassmorphism: ^3.0.0
  iconsax_flutter: ^1.0.1

  # Networking
  http: ^1.6.0

  # State Management
  provider: ^6.1.5

  # Storage
  shared_preferences: ^2.5.3

  # Utilities
  intl: ^0.20.2

  # ==========================
  # ADD THESE LATER
  # ==========================
  # image_picker: ^1.1.2
  # mobile_scanner: ^7.0.1
  # permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Example:
  #
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf